## Aljabar Matriks

- Berikan penjelasan tentang apa itu matriks
- Operasi Matrik
- Penjumlahan, Perkalian, Pengurangan, Transpose Matriks
- Buat 1 program mengalikan secara manual matrik A dan B (menggunakan perulangan)

saya disuruh membuat matriks A dan B ukuran 3x3 dan buat matriks C ukuran 3x2

In [4]:
import numpy as np
import sympy as sy

In [ ]:
A = np.array()

In [5]:
import numpy as np
A = np.array ([[1, 3],[2,1]])
B = np. array([[3, 0, 4], [-1, -2, 111]])
C = np. array ([[-2, 1],[4, 1]])
D = np .array ([[2],[6]])

print (D)

print (B)

[[2]
 [6]]
[[  3   0   4]
 [ -1  -2 111]]


Baik, berikut adalah matriks A dan B dengan ukuran 3x3:

Matriks A:

A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} \

Matriks B:

B = \begin{pmatrix} 9 & 8 & 7 \\ 6 & 5 & 4 \\ 3 & 2 & 1 \end{pmatrix} \

Untuk membuat matriks C dengan ukuran 3x2, kita bisa menggunakan angka acak atau nilai tertentu. Berikut adalah contoh matriks C dengan angka acak:

Matriks C:

C = \begin{pmatrix} 2 & 5 \\ 1 & 3 \\ 6 & 8 \end{pmatrix} \

Matriks D:

D = \begin{pmatrix} 3 & 1 & 4 \\ 1 & 5 & 9 \\ 2 & 6 & 5 \end{pmatrix} \


Dengan matriks A, B, C, dan D ini, kita dapat melakukan berbagai operasi matriks yang sesuai dengan kebutuhan kita.

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 5],
              [1, 3],
              [6, 8]])

D = np.array([[3, 1, 4],
              [1, 5, 9],
              [2, 6, 5]])

# Operasi matriks yang diminta
E = A + B
F = 2 * A
G = A @ C
H = B @ C
#A(BC) = (AB)C
I = A @ H
J = A @ B
K = J @ C

print('E = A + B:\n', E)
print('\nF = 2 * A:\n', F)
print('\nG = A @ C:\n', G)

print(G.shape)

E = A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

F = 2 * A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

G = A @ C:
 [[ 22  35]
 [ 49  83]
 [ 76 131]]
(3, 2)


In [1]:
import numpy as np

# Matriks A, B, C, dan D
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 5],
              [1, 3],
              [6, 8]])

D = np.array([[3, 1, 4],
              [1, 5, 9],
              [2, 6, 5]])

# Contoh operasi matriks
E = A + B  # Penjumlahan matriks A dan B
F = A.dot(C)  # Perkalian matriks A dan C
G = D.transpose()  # Transpose matriks D


# Menampilkan hasil operasi
print("Hasil penjumlahan matriks A dan B:")
print(E)
print("\nHasil perkalian matriks A dan C:")
print(F)
print("\nTranspose dari matriks D:")
print(G)

Hasil penjumlahan matriks A dan B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Hasil perkalian matriks A dan C:
[[ 22  35]
 [ 49  83]
 [ 76 131]]

Transpose dari matriks D:
[[3 1 2]
 [1 5 6]
 [4 9 5]]


In [2]:
import numpy as np

# Matriks A, B, dan C
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 5],
              [1, 3],
              [6, 8]])

# Hitung A(BC)
result1 = A.dot(B.dot(C))

# Hitung (AB)C
result2 = (A.dot(B)).dot(C)

# Periksa apakah hasil kedua operasi sama
if np.array_equal(result1, result2):
    print("Kedua hasil perkalian matriks A(BC) dan (AB)C sama:")
    print("A(BC) =\n", result1)
    print("(AB)C =\n", result2)
else:
    print("Kedua hasil perkalian matriks A(BC) dan (AB)C tidak sama.")

Kedua hasil perkalian matriks A(BC) dan (AB)C sama:
A(BC) =
 [[ 192  366]
 [ 561 1059]
 [ 930 1752]]
(AB)C =
 [[ 192  366]
 [ 561 1059]
 [ 930 1752]]
