# **Determinan Matriks**


Determinan matriks adalah nilai numerik yang diperoleh dari suatu matriks persegi. Matriks persegi adalah matriks yang memiliki jumlah baris sama dengan jumlah kolom. Determinan matriks adalah sifat penting dari matriks dan memiliki berbagai aplikasi dalam matematika dan ilmu terkait lainnya.

Matriks Umum
𝑛
×
𝑛
n×n:
Untuk matriks
𝑛
×
𝑛
n×n, determinan dapat dihitung dengan metode ekspansi kofaktor atau menggunakan metode lainnya seperti metode reduksi baris.

Sifat-Sifat Determinan Matriks:

1. Jika determinan suatu matriks adalah nol (
∣
𝐴
∣
=
0
∣A∣=0), maka matriks tersebut disebut sebagai matriks singular.

2. Jika determinan suatu matriks tidak nol, maka matriks tersebut disebut sebagai matriks nonsingular atau invertible.

3. Determinan dari matriks identitas
𝐼
I selalu sama dengan 1.

4. Determinan matriks transpos
𝐴
𝑇
A
T
  sama dengan determinan matriks asli
𝐴
A.

Aplikasi Determinan Matriks:

Determinan matriks digunakan dalam berbagai bidang matematika dan ilmu terapan, termasuk:

Menyelesaikan sistem persamaan linear.

Menghitung luas area dalam geometri.

Menentukan apakah matriks memiliki invers atau tidak.

Menganalisis stabilitas dalam sistem dinamika.

Contoh Penghitungan Determinan Matriks dengan Python:
Berikut adalah contoh penghitungan determinan matriks
2
×
2
2×2 dan
3
×
3
3×3 menggunakan Python:

1. Matriks 2x2:

Untuk matriks
2
×
2
2×2 yang dinyatakan sebagai:

𝐴
=
[
𝑎
𝑏
𝑐
𝑑
]
A=[
a
c
​
  
b
d
​
 ]

Determinan dari matriks
𝐴
A dihitung dengan rumus:

∣
𝐴
∣
=
𝑎
𝑑
−
𝑏
𝑐
∣A∣=ad−bc

In [1]:
# Matriks 2x2
A = [[3, 4], [1, 2]]

# Hitung determinan
det_A = A[0][0]*A[1][1] - A[0][1]*A[1][0]

print("Determinan Matriks A:", det_A)

Determinan Matriks A: 2


2. Matriks 3x3:

Untuk matriks
3
×
3
3×3 yang dinyatakan sebagai:

𝐵
=
[
𝑒
𝑓
𝑔
ℎ
𝑖
𝑗
𝑘
𝑙
𝑚
]
B=
​
  
e
h
k
​
  
f
i
l
​
  
g
j
m
​
  
​

Determinan dari matriks
𝐵
B dihitung dengan rumus ekspansi kofaktor:

∣
𝐵
∣
=
𝑒
(
𝑖
⋅
𝑚
−
𝑗
⋅
𝑙
)
−
𝑓
(
ℎ
⋅
𝑚
−
𝑗
⋅
𝑘
)
+
𝑔
(
ℎ
⋅
𝑙
−
𝑖
⋅
𝑘
)
∣B∣=e(i⋅m−j⋅l)−f(h⋅m−j⋅k)+g(h⋅l−i⋅k)

In [2]:
# Matriks 3x3
B = [[6, 1, 1], [4, -2, 5], [2, 8, 7]]

# Hitung determinan
det_B = B[0][0]*(B[1][1]*B[2][2] - B[1][2]*B[2][1]) - B[0][1]*(B[1][0]*B[2][2] - B[1][2]*B[2][0]) + B[0][2]*(B[1][0]*B[2][1] - B[1][1]*B[2][0])

print("Determinan Matriks B:", det_B)

Determinan Matriks B: -306


Penghitungan Dua Matriks dengan Program Python:

Untuk menghitung dua matriks dan menampilkan hasilnya, Anda dapat menggunakan Python sebagai berikut:

In [3]:
# Dua matriks
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

# Inisialisasi matriks hasil dengan ukuran yang sama
result = [[0, 0], [0, 0]]

# Penjumlahan dua matriks
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

# Tampilkan hasil
print("Hasil Penjumlahan Dua Matriks:")
for row in result:
    print(row)

Hasil Penjumlahan Dua Matriks:
[6, 8]
[10, 12]


Operasi Pengurangan, Perkalian, dan Pembagian Matriks dengan NumPy:

In [4]:
import numpy as np

# Dua matriks contoh
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Pengurangan matriks
subtraction_result = matrix1 - matrix2

# Perkalian matriks
multiplication_result = np.dot(matrix1, matrix2)

# Pembagian matriks (element-wise division)
division_result = np.divide(matrix1, matrix2)

print("Hasil Pengurangan Dua Matriks:")
print(subtraction_result)

print("\nHasil Perkalian Dua Matriks:")
print(multiplication_result)

print("\nHasil Pembagian Dua Matriks:")
print(division_result)

Hasil Pengurangan Dua Matriks:
[[-4 -4]
 [-4 -4]]

Hasil Perkalian Dua Matriks:
[[19 22]
 [43 50]]

Hasil Pembagian Dua Matriks:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
